helloapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.views.generic import TemplateView, RedirectView

from collection.backends import MyRegistrationView


urlpatterns = patterns('',
    url(r'^$', 'collection.views.home', name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),

    url(r'^things/$', RedirectView.as_view(pattern_name='browse')),
    url(r'^things/teams/$', 'collection.views.teams', name='teams'),
    url(r'^things/challenge/$', 'collection.views.challenge', name='challenge'),
    url(r'^things/results/$', 'collection.views.results', name='results'),
    url(r'^things/(?P<slug>[-\w]+)/$', 'collection.views.thing_detail', name='thing_detail'),
    # new line we're adding!
    url(r'^things/(?P<slug>[-\w]+)/edit/$', 'collection.views.edit_thing', name='edit_thing'),


    url(r'^browse/$', RedirectView.as_view(pattern_name='browse')),
    #url(r'^browse/name/$', 'collection.views.browse_by_name', name='browse'),
    #url(r'^browse/name/(?P<initial>[-\w]+)/$', 'collection.views.browse_by_name', name='browse_by_name'),

    # password reset urls
    url(r'^accounts/password/reset/$', password_reset,
        {'template_name': 'registration/password_reset_form.html'},
        name="password_reset"),
    url(r'^accounts/password/reset/done/$',
        password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name="password_reset_done"),
    url(r'^accounts/password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name="password_reset_confirm"),
    url(r'^accounts/password/done/$', password_reset_complete,
        {'template_name': 'registration/password_reset_complete.html'},
        name="password_reset_complete"),

    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/create_thing/$', 'collection.views.create_thing', name='registration_create_thing'),

    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

collection/models.py
from django.contrib.auth.models import User
from django.db import models
from django import forms

class Person(models.Model):
	team = models.ForeignKey('Team', blank=True, null=True)
	user = models.OneToOneField(User, blank=True, null=True)

	def __str__(self):
		return "{} ({})".format(self.user.username, self.team.name)


class Team(models.Model):
	name = models.CharField(max_length=255, unique=True)
	description = models.TextField(blank=True)
	slug = models.SlugField(unique=True)

	def game_count(self):
		return self.games_as_challenger.count() + self.games_as_opponent.count()

	def __str__(self):
		return self.name

class Game(models.Model):
	creator = models.ForeignKey(Person)
	challenger = models.ForeignKey(Team, related_name="games_as_challenger")
	opponent = models.ForeignKey(Team, related_name="games_as_opponent")
	winner = models.ForeignKey(Team, related_name="games_as_winner", null=True, blank=True)
	loser = models.ForeignKey(Team, related_name="games_as_loser", null=True, blank=True)

	def __str__(self):
		return "{} vs {}".format(self.challenger.name, self.opponent.name)

collection/forms.py
from django.forms import ModelForm
from django import forms
from django.utils.text import slugify
from collection.models import Person, Team, Game

class PersonForm(ModelForm):
    team_name = forms.CharField(max_length=255, required=False)
    description = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Person
        fields = ('team',)

    def clean(self):
        team_name = self.cleaned_data.get('team_name')
        team = self.cleaned_data.get('team')

        if not team and not team_name:
            raise forms.ValidationError('You must either select a team or enter a new team name')

        if team and team_name:
            raise forms.ValidationError('You can only enter a team name if you have not selected an existing team')

    def save(self, commit=True):
        obj = super().save(commit=False)
        team_name = self.cleaned_data.get('team_name')
        if team_name:
            team, created = Team.objects.get_or_create(name=team_name)
            team.slug = slugify(team_name)
            obj.team = team
        else:
            team = self.cleaned_data['team']
        team.description = self.cleaned_data.get('description')
        team.save()
        if commit:
            obj.save()
        return obj


class GameForm(ModelForm):
    def __init__(self, *args, **kwargs):
        person = kwargs.pop('person')
        super().__init__(*args, **kwargs)
        self.fields['opponent'].queryset = Team.objects.exclude(id=person.team.id)

    class Meta:
        model = Game
        fields = ('opponent',)


class GameAdminForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance:
            qs = Team.objects.filter(id__in=(self.instance.challenger_id, self.instance.opponent_id))
            self.fields['winner'].queryset = qs

    def save(self, commit=True):
        obj = super().save(commit=False)
        if obj.winner_id:
            if obj.winner_id == obj.challenger_id:
                obj.loser_id = obj.opponent_id
            else:
                obj.loser_id = obj.challenger_id
        if commit:
            obj.save()
        return obj

    class Meta:
        model = Game
        exclude = ('loser',)

collection/views.py
from django.shortcuts import render, redirect
from collection.models import Person, Game, Team
from collection.forms import PersonForm, GameForm
from django.template.defaultfilters import slugify
from django.contrib.auth.decorators import login_required
from django.http import Http404

def home(request):
  persons = Person.objects.all()

  return render(request, 'index.html', {
	   'persons': persons,
  })

def thing_detail(request, slug):
    person = Person.objects.get(user__username=slug)
    context = {'person':person}
    context['game_count'] = person.team.games_as_opponent.count() + person.team.games_as_challenger.count()
    context['win_count'] = person.team.games_as_winner.count()
    context['lose_count'] = person.team.games_as_loser.count()
    return render(request, 'things/thing_detail.html', context)

@login_required
def edit_thing(request, slug):
  person = Person.objects.get(user__username=slug)
  if person.user != request.user:
      raise Http404
  form_class = PersonForm
  if request.method == 'POST':
      form = form_class(data=request.POST, instance=person)
      if form.is_valid():
        form.save()
        return redirect('thing_detail', slug=person.user.username)
  else:
      form = form_class(instance=person, initial={'description': person.team.description})
  return render(request, 'things/edit_thing.html', { 'person': person,'form': form, })

def create_thing(request):
    form_class = PersonForm
    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            person = form.save(commit=False)
            person.user = request.user
            person.save()
            return redirect('thing_detail', slug=person.user.username)
    else:
        form = form_class()
    return render(request, 'things/create_thing.html', {
        'form': form,
    })

def challenge(request):
    person = request.user.person
    if request.method == 'POST':
        form = GameForm(request.POST, person=person)
        if form.is_valid():
            game = form.save(commit=False)
            person = request.user.person
            game.creator = person
            game.challenger = person.team
            game.save()
            return redirect('thing_detail', slug=person.user.username)
    else:
        form = GameForm(person=person)
    return render(request, 'things/challenge.html', {'form': form})

def teams(request):
    return render(request, 'things/teams.html', {'teams': Team.objects.all()})

def results(request):
    games_with_result = Game.objects.exclude(winner=None)
    return render(request, 'things/results.html', {'games': games_with_result})

templates/about.html
{% extends 'index.html' %}

{% block inner_content %}
		<h1>About page</h1>

<p>About content.</p>

{% endblock %}

templates/contact.html
{% extends 'index.html' %}
{% block inner_content %}
<h1>Contact page</h1>
<p>Contact content.</p>
{% endblock %}

templates/index.html
{% load staticfiles %}

{% block extra_head_top %}
	<link rel="stylesheet" href="{% static 'base_theme/bootstrap_css/bootstrap.min.css' %}" />
{% endblock %}
{% block main_nav %}
		<li><a href="{% url 'home' %}">Home</a></li> <li><a href="{% url 'about' %}">About</a></li>
		<li><a href="{% url 'contact' %}">Contact</a></li>
		<li><a href="http://localhost:8001/admin">Admin</a> </li>
		{% if user.is_authenticated %} <li>
		<a href="{% url 'auth_logout' %}">Logout</a> </li>
		{% else %} <li>
		<a href="{% url 'auth_login' %}">Login</a> </li>
		<li>
		<a href="{% url 'registration_register'%}">Create Account</a>
		</li>
		{% endif %}
{% endblock %}




{% block inner_content %}
			<h1>Welcome to the Foosball App!</h1>


			{% for person in persons %}

			  {% if user == person.user %}
			    Welcome back {{ user }} !
	       <h2><a href="{% url 'thing_detail' slug=person.user.username %}"> Your Profile
		  {% endif %}




{% endfor %}
{% endblock %}

{% block extra_footer_js %}
    <script src="{% static 'base_theme/js/jquery.min.css' %}"></script>
    <script src="{% static 'base_theme/js/bootstrap.min.css' %}"></script>
{% endblock %}

templates/things/challenge.html
{% extends 'index.html' %}
{% block inner_content %}
<h1>Challenge another team</h1>
<form role="form" action="" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}

    {{ form.opponent.label_tag }}
    {{ form.opponent }}
    {{ form.opponent.errors }}
    <input type='submit'>
</form>
{% endblock %}

templates/things/create_thing.html
{% extends 'index.html' %}

{% block inner_content %}
<h2>Create a new team or join one below:</h2>
<form role="form" action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}

templates/things/edit_thing.html
{% extends 'index.html' %}
{% block inner_content %}
<form role="form" action="" method="post">
	{% csrf_token %}
	{{ form.non_field_errors }}

	<div>
		{{ form.team.label_tag }}
		{{ form.team }}
		{{ form.team.errors }}
	</div>
	<div>
		{{ form.team_name.label_tag }}
		{{ form.team_name }}
		{{ form.team_name.errors }}
	</div>
	<div>
		{{ form.description.label_tag }}
		{{ form.description }}
		{{ form.description.errors }}
	</div>
		<button type="submit">Submit</button>
</form>


{% endblock %}

templates/things/results.html
{% extends 'index.html' %}
{% block inner_content %}
<h1>Game results</h1>

<ul>
  {% for game in games %}
    <li>{{ game }} - Winner: {{ game.winner }}</li>
  {% empty %}
    <li>There are no completed games.
  {% endfor %}
</ul>
{% endblock %}

templates/things/teams.html
{% extends 'index.html' %}
{% block inner_content %}
<h1>Teams</h1>

{% for team in teams %}
<h2>{{ team.name }}</h2>
<ul>
  <li>Members:
    <ul>
      {% for person in team.person_set.all %}
      <li>{{ person.user.username }}</li>
      {% endfor %}
    </ul>
  </li>
  <li>Total games: {{ team.game_count }}</li>
	<li>Games won: {{ team.games_as_winner.count }}</li>
	<li>Games lost: {{ team.games_as_loser.count }}</li>
</ul>
{% endfor %}
{% endblock %}

templates/things/thing_detail.html
{% extends 'index.html' %}
{% block inner_content %}
<h1>Your Profile</h1>
<p>Your Username: {{ user }}</p>
<p>Your Email: {{ user.email }}</p>
{% with person.team as team %}
	<p>On Team: {{ team.name }}</p>
	<p>Description of Team: {{ team.description|linebreaksbr }}</p>
		{% if user == person.user %}
			<a href="{% url 'edit_thing' slug=person.user.username %}">Edit me!</a>
		{% endif %}
	<p>Total games: {{ team.game_count }}</p>
	<p>Games won: {{ team.games_as_winner.count }}</p>
	<p>Games lost: {{ team.games_as_loser.count }}</p>
{% endwith %}
<a href="{% url "challenge" %}">Challenge a team</a>
{% endblock %}